import { CONFIG_NAMES, MESSAGE_LEVEL_TYPES } from './const';

export const LOG_LEVELS_ON_FAIL_DEFAULT: Record<CONFIG_NAMES, MESSAGE_LEVEL_TYPES> = {
  [CONFIG_NAMES.local]: MESSAGE_LEVEL_TYPES.warning,
  [CONFIG_NAMES.development]: MESSAGE_LEVEL_TYPES.debug,
  [CONFIG_NAMES.production]: MESSAGE_LEVEL_TYPES.debug,
};

export const LOG_LEVELS_ON_SUCCESS_DEFAULT: Record<CONFIG_NAMES, MESSAGE_LEVEL_TYPES> = {
  [CONFIG_NAMES.local]: MESSAGE_LEVEL_TYPES.error,
  [CONFIG_NAMES.development]: MESSAGE_LEVEL_TYPES.debug,
  [CONFIG_NAMES.production]: MESSAGE_LEVEL_TYPES.warning,
};

export const LOG_LEVELS_TO_SEND_ON_SUCCESS_DEFAULT: Record<CONFIG_NAMES, MESSAGE_LEVEL_TYPES> = {
  [CONFIG_NAMES.local]: MESSAGE_LEVEL_TYPES.nothing,
  [CONFIG_NAMES.development]: MESSAGE_LEVEL_TYPES.warning,
  [CONFIG_NAMES.production]: MESSAGE_LEVEL_TYPES.warning,
};

export const LOG_LEVELS_TO_SEND_ON_FAIL_DEFAULT: Record<CONFIG_NAMES, MESSAGE_LEVEL_TYPES> = {
  [CONFIG_NAMES.local]: MESSAGE_LEVEL_TYPES.nothing,
  [CONFIG_NAMES.development]: MESSAGE_LEVEL_TYPES.warning,
  [CONFIG_NAMES.production]: MESSAGE_LEVEL_TYPES.warning,
};
